# Generated by Django 2.1.7 on 2019-04-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programminglanguage',
            name='id',
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
