# Generated by Django 2.1.7 on 2019-04-03 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthapp', '0002_auto_20190402_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgrammingLanguage',
        ),
    ]
